---
version: 0.0
os: linux
files:

  - source: app
    destination: /arena/app
  - source: nodejs
    destination: /arena/nodejs
  - source: env
    destination: /tmp/env
  - source: service/app.service
    destination: /usr/lib/systemd/system/

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
  ValidateService:
    - location: scripts/check_service.sh
      timeout: 30

