/**
 * Pricecaster Service.
 *
 * Pyth Product String to ASA ID
 *
 * Copyright 2022 Randlabs Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const PythSymbolToAsaIdTestnet = new Map([
  ['Equity.US.NFLX/USD', undefined],
  ['Crypto.SCNSOL/USD', undefined],
  ['Crypto.SRM/USD', undefined],
  ['Crypto.ETH/USD', 90650110],
  ['Equity.US.AAPL/USD', undefined],
  ['Crypto.BTC/USD', 88808609],
  ['Crypto.BNB/USD', undefined],
  ['Equity.US.AMC/USD', undefined],
  ['Crypto.SOL/USD', undefined],
  ['Equity.US.TSLA/USD', undefined],
  ['Crypto.SBR/USD', undefined],
  ['Crypto.FIDA/USD', undefined],
  ['Crypto.ATOM/USD', undefined],
  ['Crypto.STSOL/USD', undefined],
  ['Crypto.DOGE/USD', undefined],
  ['FX.USD/CAD', undefined],
  ['Equity.US.GE/USD', undefined],
  ['Crypto.COPE/USD', undefined],
  ['Crypto.PORT/USD', undefined],
  ['Crypto.BCH/USD', undefined],
  ['Crypto.DOT/USD', undefined],
  ['Crypto.FTM/USD', undefined],
  ['Crypto.MNGO/USD', undefined],
  ['Crypto.C98/USD', undefined],
  ['FX.USD/RUB', undefined],
  ['Metal.XAU/USD', undefined],
  ['Crypto.MATIC/USD', undefined],
  ['Crypto.FTT/USD', undefined],
  ['Crypto.STEP/USD', undefined],
  ['Crypto.USDT/USD', undefined],
  ['FX.AUD/USD', undefined],
  ['FX.EUR/USD', undefined],
  ['Crypto.ONE/USD', undefined],
  ['Equity.US.SPY/USD', undefined],
  ['Crypto.SLND/USD', undefined],
  ['FX.NZD/USD', undefined],
  ['Crypto.JET/USD', undefined],
  ['FX.USD/SGD', undefined],
  ['Crypto.LTC/USD', undefined],
  ['FX.USD/CHF', undefined],
  ['FX.USD/ZAR', undefined],
  ['Crypto.AVAX/USD', undefined],
  ['Crypto.ORCA/USD', undefined],
  ['Crypto.NEAR/USD', undefined],
  ['FX.USD/MXN', undefined],
  ['Equity.US.GOOG/USD', undefined],
  ['Crypto.UST/USD', undefined],
  ['Crypto.HXRO/USD', undefined],
  ['Crypto.PAI/USD', undefined],
  ['Equity.US.GME/USD', undefined],
  ['FX.USD/HKD', undefined],
  ['Crypto.ADA/USD', undefined],
  ['Crypto.MSOL/USD', undefined],
  ['Crypto.MIR/USD', undefined],
  ['Crypto.SNY/USD', undefined],
  ['FX.USD/CNH', undefined],
  ['Crypto.INJ/USD', undefined],
  ['Crypto.ALGO/USD', 0],
  ['Equity.US.AMZN/USD', undefined],
  ['Crypto.MER/USD', undefined],
  ['Crypto.USDC/USD', 10458941],
  ['FX.USD/JPY', undefined],
  ['FX.GBP/USD', undefined],
  ['Equity.US.QQQ/USD', undefined],
  ['Crypto.RAY/USD', undefined],
  ['Crypto.LUNA/USD', undefined]
])

// ----------------------------------------------------------------------------
// Mainnet ASA IDs
// ----------------------------------------------------------------------------

export const PythSymbolToAsaIdMainnet = new Map([
  ['Equity.US.NFLX/USD', undefined],
  ['Crypto.SCNSOL/USD', undefined],
  ['Crypto.SRM/USD', undefined],
  ['Crypto.ETH/USD', undefined],
  ['Equity.US.AAPL/USD', undefined],
  ['Crypto.BTC/USD', undefined],
  ['Crypto.BNB/USD', undefined],
  ['Equity.US.AMC/USD', undefined],
  ['Crypto.SOL/USD', undefined],
  ['Equity.US.TSLA/USD', undefined],
  ['Crypto.SBR/USD', undefined],
  ['Crypto.FIDA/USD', undefined],
  ['Crypto.ATOM/USD', undefined],
  ['Crypto.STSOL/USD', undefined],
  ['Crypto.DOGE/USD', undefined],
  ['FX.USD/CAD', undefined],
  ['Equity.US.GE/USD', undefined],
  ['Crypto.COPE/USD', undefined],
  ['Crypto.PORT/USD', undefined],
  ['Crypto.BCH/USD', undefined],
  ['Crypto.DOT/USD', undefined],
  ['Crypto.FTM/USD', undefined],
  ['Crypto.MNGO/USD', undefined],
  ['Crypto.C98/USD', undefined],
  ['FX.USD/RUB', undefined],
  ['Metal.XAU/USD', undefined],
  ['Crypto.MATIC/USD', undefined],
  ['Crypto.FTT/USD', undefined],
  ['Crypto.STEP/USD', undefined],
  ['Crypto.USDT/USD', undefined],
  ['FX.AUD/USD', undefined],
  ['FX.EUR/USD', undefined],
  ['Crypto.ONE/USD', undefined],
  ['Equity.US.SPY/USD', undefined],
  ['Crypto.SLND/USD', undefined],
  ['FX.NZD/USD', undefined],
  ['Crypto.JET/USD', undefined],
  ['FX.USD/SGD', undefined],
  ['Crypto.LTC/USD', undefined],
  ['FX.USD/CHF', undefined],
  ['FX.USD/ZAR', undefined],
  ['Crypto.AVAX/USD', undefined],
  ['Crypto.ORCA/USD', undefined],
  ['Crypto.NEAR/USD', undefined],
  ['FX.USD/MXN', undefined],
  ['Equity.US.GOOG/USD', undefined],
  ['Crypto.UST/USD', undefined],
  ['Crypto.HXRO/USD', undefined],
  ['Crypto.PAI/USD', undefined],
  ['Equity.US.GME/USD', undefined],
  ['FX.USD/HKD', undefined],
  ['Crypto.ADA/USD', undefined],
  ['Crypto.MSOL/USD', undefined],
  ['Crypto.MIR/USD', undefined],
  ['Crypto.SNY/USD', undefined],
  ['FX.USD/CNH', undefined],
  ['Crypto.INJ/USD', undefined],
  ['Crypto.ALGO/USD', 0],
  ['Equity.US.AMZN/USD', undefined],
  ['Crypto.MER/USD', undefined],
  ['Crypto.USDC/USD', 31566704],
  ['FX.USD/JPY', undefined],
  ['FX.GBP/USD', undefined],
  ['Equity.US.QQQ/USD', undefined],
  ['Crypto.RAY/USD', undefined],
  ['Crypto.LUNA/USD', undefined]
])
